#kafka :
#  bootstrap-servers: localhost:9092
#  consumer:
#    group-id : group_id
#    auto-offset-reset: latest
#    enable-auto-commit: true
#    auto-commit-interval: 100
#    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
#    max-poll-records: 100
#    fetch-max-wait: 1000
#  producer:
#    bootstrap-servers: localhost:9092
#    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
#    retries: 2
#    acks: 1
#    client-id: heimdall-agent-manager-local
#    properties.enable.idempotence : false